services:
  postgres:
    image: postgres:15-alpine
    container_name: weather-db
    environment:
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_pass
      POSTGRES_DB: weather_mcp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mcp-network

  redis:
    image: redis:7-alpine
    container_name: weather-cache
    ports:
      - "6379:6379"
    networks:
      - mcp-network

  mcp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: weather-mcp-server
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mcp_user:mcp_pass@postgres:5432/weather_mcp
      - REDIS_URL=redis://redis:6379
      - WEATHER_API_KEY=57e0b31962ae34800b8c4142095d57fa
      - PORT=3000
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mcp-network:
    driver: bridge